

def configure(c):
    c.define('NEART_TEST', 1)
    c.write_config_header('test_config.h')

def build(c):
    pass

def test(c):
    tests = [ 'test_' + f for f in [ 'arith' ] ]
    for test in tests:
        t = __import__(test, globals(), locals(), [], 0)
        print(t.code)
