

def configure(c):
    c.define('NEART_TEST', 1)
    c.write_config_header('test_config.h')

def build(c):
    includes = '. ../src ../visual ../third/klib'
    c.program( source = 'test_ast.c',
               target = 'neart_test_ast',
               use = 'neart_core neart_debug',
               includes = includes,
             )
