
def configure(c):
    pass


def build(c):

    includes = '. vm syntax semantic util type ncode visual ../third/klib'
    c.objects( source = 'visual/dot_syntax_tree.c ncode/rcode_debug.c', 
               target = 'neart_debug',
               includes = includes,
             )

    c.objects( source = 'ncode/code.c ncode/cpool.c ncode/nfile.c', 
               target = 'neart_code',
               includes = includes,
             )

    c.objects( source = 'syntax/neart.l syntax/neart.y syntax/ast.c ' +
                        'semantic/gpir.c semantic/sem.c semantic/typecheck.c ' +
                        'util/symt.c semantic/types.c semantic/binding.c ncode/rcode_gen.c ncode/qcode.c ' +
                        'ncode/cpool_builder.c ', 
               target = 'neart_core',
               includes = includes,
             )

    c.program( source = 'main.c',
            target = 'neartc',
            use = 'neart_core neart_code klib neart_debug',
            includes = includes
          )

    c.objects( source = 'vm/vm.c',
               target = 'neart_vm',
               includes = includes,
             )

    c.program( source = 'vm/main.c',
               target = 'nvm',
               use = 'neart_vm neart_code',
               includes = includes,
             )
