
def configure(c):
    pass


def build(c):

    includes = '. visual ../third/klib'
    c.objects( source = 'visual/dot_syntax_tree.c', 
               target = 'neart_debug',
               includes = includes,
             )

    c.objects( source = 'neart.l neart.y ast.c gpir.c sem.c code.c symt.c types.c', 
               target = 'neart_core',
               includes = includes,
             )

    c.program( source = 'main.c',
            target = 'neartc',
            use = 'neart_core klib neart_debug',
            includes = includes
          )
